'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { api, json, Asesor, Usuario } from '@/lib/api';
interface Canal { id: number; tipo: 'REPARTIDOR' | 'ASESOR'; nombre: string; numeroVisible?: string | null; phoneNumberId?: string | null; wabaId?: string | null; asesorId?: number | null; activo: boolean; modoCoexistencia: boolean; estadoIntegracion: 'PENDIENTE_CONFIGURACION' | 'ACTIVO' | 'INACTIVO' | 'ERROR'; asesor?: Asesor | null; }
interface Config { nombrePlantillaInicio?: string | null; idiomaPlantillaInicio: string; mensajeEspera: string; }

export function Channels({ usuario, version, onChange }: { usuario: Usuario; version: number; onChange: () => void }) {
  const [canales, setCanales] = useState<Canal[]>([]); const [asesores, setAsesores] = useState<Asesor[]>([]); const [config, setConfig] = useState<Config>();
  const [tipo, setTipo] = useState<'REPARTIDOR' | 'ASESOR'>('ASESOR'); const [nombre, setNombre] = useState(''); const [numeroVisible, setNumeroVisible] = useState(''); const [phoneNumberId, setPhoneNumberId] = useState(''); const [wabaId, setWabaId] = useState(''); const [asesorId, setAsesorId] = useState(''); const [modoCoexistencia, setModoCoexistencia] = useState(true);
  const [error, setError] = useState(''); const [exito, setExito] = useState(''); const [busy, setBusy] = useState(false);
  const admin = usuario.rol === 'ADMIN';
  const cargar = useCallback(async () => { try { const [c, a, f] = await Promise.all([api<Canal[]>('/canales-whatsapp'), api<Asesor[]>('/asesores'), api<Config>('/configuracion-whatsapp')]); setCanales(c); setAsesores(a); setConfig(f); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudieron cargar canales'); } }, []);
  useEffect(() => { void cargar(); }, [cargar, version]);
  async function ejecutar(ruta: string, cuerpo: unknown, method: 'POST' | 'PATCH' = 'PATCH') { setBusy(true); setError(''); setExito(''); try { await api(ruta, json(method, cuerpo)); await cargar(); onChange(); setExito('Cambios guardados'); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar'); } finally { setBusy(false); } }
  function crear(e: FormEvent) { e.preventDefault(); void ejecutar('/canales-whatsapp', { tipo, nombre, numeroVisible, phoneNumberId, wabaId, asesorId: tipo === 'ASESOR' ? Number(asesorId) : undefined, modoCoexistencia: tipo === 'ASESOR' && modoCoexistencia, estadoIntegracion: 'PENDIENTE_CONFIGURACION', activo: false }, 'POST'); }
  return <div className="p-5 md:p-8 max-w-7xl mx-auto"><div className="eyebrow mb-2">Integraciones</div><h1 className="text-3xl font-bold">Canales WhatsApp</h1><p className="muted mt-2">Cada número tiene un Phone Number ID propio. Activa un canal cuando la conexión en Meta esté validada.</p>
    {error && <p role="alert" className="mt-4 p-3 bg-red-50 text-red-700 rounded-lg">{error}</p>}{exito && <p role="status" className="mt-4 p-3 bg-green-50 text-green-700 rounded-lg">{exito}</p>}
    <div className="grid md:grid-cols-2 gap-4 mt-5">{canales.map(c => <article key={c.id} className="card p-5"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{c.nombre}</h2><p className="text-sm muted">{c.tipo} · {c.numeroVisible || 'Sin número visible'}</p></div><span className={`badge h-fit ${c.activo ? '' : 'badge-off'}`}>{c.activo ? 'Activo' : 'Inactivo'}</span></div><dl className="text-sm mt-4 grid grid-cols-[130px_1fr] gap-y-2"><dt className="muted">Phone Number ID</dt><dd className="break-all">{c.phoneNumberId || 'Pendiente'}</dd><dt className="muted">WABA ID</dt><dd className="break-all">{c.wabaId || 'Pendiente'}</dd><dt className="muted">Asesor</dt><dd>{c.asesor?.usuario.nombre || '—'}</dd><dt className="muted">Coexistence</dt><dd>{c.modoCoexistencia ? 'Sí' : 'No'}</dd><dt className="muted">Integración</dt><dd>{c.estadoIntegracion}</dd></dl>{admin && <div className="flex gap-2 mt-4"><button disabled={busy} className="button button-light" onClick={() => void ejecutar(`/canales-whatsapp/${c.id}`, { activo: !c.activo, estadoIntegracion: c.activo ? 'INACTIVO' : 'ACTIVO' })}>{c.activo ? 'Desactivar' : 'Validado y activar'}</button>{!c.activo && <button disabled={busy} className="button button-light" onClick={() => { const nuevo = window.prompt('Nuevo Phone Number ID', c.phoneNumberId || ''); if (nuevo) void ejecutar(`/canales-whatsapp/${c.id}`, { phoneNumberId: nuevo }); }}>Editar ID</button>}</div>}</article>)}</div>
    {admin && <div className="grid lg:grid-cols-2 gap-5 mt-6"><form onSubmit={crear} className="card p-5 grid gap-3"><h2 className="font-bold">Crear canal</h2><select aria-label="Tipo de canal" className="field" value={tipo} onChange={e => setTipo(e.target.value as 'REPARTIDOR' | 'ASESOR')}><option value="ASESOR">Asesor</option><option value="REPARTIDOR">Repartidor</option></select><input aria-label="Nombre del canal" className="field" placeholder="Nombre" required value={nombre} onChange={e => setNombre(e.target.value)}/><input aria-label="Número visible" className="field" placeholder="Número visible" required value={numeroVisible} onChange={e => setNumeroVisible(e.target.value)}/><input aria-label="Phone Number ID" className="field" placeholder="Phone Number ID" required value={phoneNumberId} onChange={e => setPhoneNumberId(e.target.value)}/><input aria-label="WABA ID" className="field" placeholder="WABA ID" value={wabaId} onChange={e => setWabaId(e.target.value)}/>{tipo === 'ASESOR' && <><select aria-label="Asesor" className="field" required value={asesorId} onChange={e => setAsesorId(e.target.value)}><option value="">Selecciona asesor</option>{asesores.map(a => <option key={a.id} value={a.id}>{a.usuario.nombre} {a.usuario.apellido}</option>)}</select><label className="text-sm flex gap-2"><input type="checkbox" checked={modoCoexistencia} onChange={e => setModoCoexistencia(e.target.checked)}/> WhatsApp Business App + Cloud API</label></>}<button className="button button-primary" disabled={busy}>Guardar canal</button></form><form onSubmit={e => { e.preventDefault(); if (config) void ejecutar('/configuracion-whatsapp', config); }} className="card p-5 grid gap-3"><h2 className="font-bold">Primer contacto</h2><label className="text-sm">Plantilla aprobada<input className="field mt-1" placeholder="Nombre exacto en Meta" value={config?.nombrePlantillaInicio || ''} onChange={e => setConfig(config ? { ...config, nombrePlantillaInicio: e.target.value } : undefined)}/></label><label className="text-sm">Idioma de plantilla<input className="field mt-1" value={config?.idiomaPlantillaInicio || 'es'} onChange={e => setConfig(config ? { ...config, idiomaPlantillaInicio: e.target.value } : undefined)}/></label><label className="text-sm">Respuesta automática del repartidor<input className="field mt-1" value={config?.mensajeEspera || ''} onChange={e => setConfig(config ? { ...config, mensajeEspera: e.target.value } : undefined)}/></label><p className="text-xs muted">Configura en Meta una plantilla aprobada con dos variables: cliente y asesor. NEXO envía esa plantilla desde el número del asesor.</p><button className="button button-primary" disabled={busy || !config}>Guardar configuración</button></form></div>}
  </div>;
}
