'use client';
import { FormEvent, useState } from 'react';
import { api, json, Asesor, Grupo, Opcion } from '@/lib/api';

export function GrupoEditor({ grupos, onChange }: { grupos: Grupo[]; onChange: () => void }) {
  const [actual, setActual] = useState<Grupo>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function guardar(e: FormEvent) { e.preventDefault(); if (!actual) return; setBusy(true); setError(''); try { await api(`/grupos/${actual.id}`, json('PATCH', { nombre: actual.nombre, descripcion: actual.descripcion || '' })); setActual(undefined); onChange(); } catch (err) { setError(err instanceof Error ? err.message : 'Error'); } finally { setBusy(false); } }
  return <div className="card p-5 mt-5"><h2 className="font-bold mb-3">Editar grupo</h2><select aria-label="Grupo a editar" className="field max-w-sm" value={actual?.id || ''} onChange={e => setActual(grupos.find(g => g.id === Number(e.target.value)))}><option value="">Seleccionar grupo</option>{grupos.map(g => <option key={g.id} value={g.id}>{g.nombre}</option>)}</select>{actual && <form onSubmit={guardar} className="flex flex-wrap gap-3 items-end mt-4"><label className="text-sm flex-1 min-w-[180px]">Nombre<input className="field mt-2" required value={actual.nombre} onChange={e => setActual({ ...actual, nombre: e.target.value })}/></label><label className="text-sm flex-1 min-w-[180px]">Descripción<input className="field mt-2" value={actual.descripcion || ''} onChange={e => setActual({ ...actual, descripcion: e.target.value })}/></label><button disabled={busy} className="button button-primary">Guardar</button></form>}{error && <p role="alert" className="text-red-700 text-sm mt-2">{error}</p>}</div>;
}

export function OpcionEditor({ opciones, grupos, onChange }: { opciones: Opcion[]; grupos: Grupo[]; onChange: () => void }) {
  const [actual, setActual] = useState<Opcion>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function guardar(e: FormEvent) { e.preventDefault(); if (!actual) return; setBusy(true); setError(''); try { await api(`/opciones-whatsapp/${actual.id}`, json('PATCH', { titulo: actual.titulo, descripcion: actual.descripcion || '', identificadorExterno: actual.identificadorExterno, grupoId: actual.grupoId, orden: actual.orden })); setActual(undefined); onChange(); } catch (err) { setError(err instanceof Error ? err.message : 'Error'); } finally { setBusy(false); } }
  return <div className="card p-5 mt-5"><h2 className="font-bold mb-3">Editar opción y orden</h2><select aria-label="Opción a editar" className="field max-w-sm" value={actual?.id || ''} onChange={e => setActual(opciones.find(o => o.id === Number(e.target.value)))}><option value="">Seleccionar opción</option>{opciones.map(o => <option key={o.id} value={o.id}>{o.titulo}</option>)}</select>{actual && <form onSubmit={guardar} className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mt-4 items-end"><label className="text-sm">Título<input className="field mt-2" maxLength={24} required value={actual.titulo} onChange={e => setActual({ ...actual, titulo: e.target.value })}/></label><label className="text-sm">Descripción<input className="field mt-2" maxLength={72} value={actual.descripcion || ''} onChange={e => setActual({ ...actual, descripcion: e.target.value })}/></label><label className="text-sm">Grupo<select className="field mt-2" value={actual.grupoId} onChange={e => setActual({ ...actual, grupoId: Number(e.target.value) })}>{grupos.map(g => <option key={g.id} value={g.id}>{g.nombre}</option>)}</select></label><label className="text-sm">Orden<input className="field mt-2" type="number" required value={actual.orden} onChange={e => setActual({ ...actual, orden: Number(e.target.value) })}/></label><button disabled={busy} className="button button-primary">Guardar</button></form>}{error && <p role="alert" className="text-red-700 text-sm mt-2">{error}</p>}</div>;
}

export function AsesorEditor({ asesores, grupos, onChange }: { asesores: Asesor[]; grupos: Grupo[]; onChange: () => void }) {
  const [asesorId, setAsesorId] = useState(''); const [grupoId, setGrupoId] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function guardar(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { await api(`/asesores/${asesorId}`, json('PATCH', { grupoId: Number(grupoId) })); setAsesorId(''); setGrupoId(''); onChange(); } catch (err) { setError(err instanceof Error ? err.message : 'Error'); } finally { setBusy(false); } }
  return <div className="card p-5 mt-5"><h2 className="font-bold mb-1">Cambiar grupo de asesor</h2><p className="text-xs muted mb-4">Cierra o reasigna sus conversaciones operativas antes de moverlo.</p><form onSubmit={guardar} className="flex flex-wrap gap-3 items-end"><label className="text-sm flex-1 min-w-[180px]">Asesor<select className="field mt-2" required value={asesorId} onChange={e => setAsesorId(e.target.value)}><option value="">Seleccionar</option>{asesores.map(a => <option key={a.id} value={a.id}>{a.usuario.nombre} {a.usuario.apellido}</option>)}</select></label><label className="text-sm flex-1 min-w-[180px]">Grupo nuevo<select className="field mt-2" required value={grupoId} onChange={e => setGrupoId(e.target.value)}><option value="">Seleccionar</option>{grupos.filter(g => g.activo).map(g => <option key={g.id} value={g.id}>{g.nombre}</option>)}</select></label><button className="button button-primary" disabled={busy}>Guardar</button></form>{error && <p role="alert" className="text-red-700 text-sm mt-2">{error}</p>}</div>;
}
