'use client';
import { FormEvent, useEffect, useState } from 'react';
import { api, json, Asesor, Grupo, Opcion, Rol, Usuario } from '@/lib/api';
import { AsesorEditor, GrupoEditor, OpcionEditor } from './Editors';

type Vista = 'asesores' | 'grupos' | 'opciones' | 'usuarios' | 'configuracion' | 'auditoria';
interface Cuenta { id: number; nombre: string; apellido: string; correo: string; rol: Rol; activo: boolean; }
interface Auditoria { id: number; accion: string; entidad: string; entidadId: string; fecha: string; usuario?: { nombre: string; apellido: string }; }
interface Configuracion { modo: string; phoneNumberIdConfigurado: boolean; wabaIdConfigurado: boolean; accessTokenConfigurado: boolean; appSecretConfigurado: boolean; verifyTokenConfigurado: boolean; webhook: string; numeroVisible?: string; }

export function Management({ vista, usuario, version, onChange }: { vista: Vista; usuario: Usuario; version: number; onChange: () => void }) {
  const [asesores, setAsesores] = useState<Asesor[]>([]); const [grupos, setGrupos] = useState<Grupo[]>([]); const [opciones, setOpciones] = useState<Opcion[]>([]); const [cuentas, setCuentas] = useState<Cuenta[]>([]); const [auditoria, setAuditoria] = useState<Auditoria[]>([]); const [config, setConfig] = useState<Configuracion>();
  const [error, setError] = useState(''); const [exito, setExito] = useState(''); const [busy, setBusy] = useState(false);
  const [grupoNombre, setGrupoNombre] = useState(''); const [grupoDescripcion, setGrupoDescripcion] = useState('');
  const [opTitulo, setOpTitulo] = useState(''); const [opCodigo, setOpCodigo] = useState(''); const [opGrupo, setOpGrupo] = useState(''); const [opOrden, setOpOrden] = useState('1');
  const [nombre, setNombre] = useState(''); const [apellido, setApellido] = useState(''); const [correo, setCorreo] = useState(''); const [password, setPassword] = useState(''); const [rol, setRol] = useState<Rol>('ASESOR');
  const [asesorUsuario, setAsesorUsuario] = useState(''); const [asesorGrupo, setAsesorGrupo] = useState('');
  useEffect(() => { const cargar = async () => { try {
    if (vista === 'asesores') { const [a, g, u] = await Promise.all([api<Asesor[]>('/asesores'), api<Grupo[]>('/grupos'), usuario.rol === 'ADMIN' ? api<Cuenta[]>('/usuarios') : Promise.resolve([])]); setAsesores(a); setGrupos(g); setCuentas(u); }
    if (vista === 'grupos') setGrupos(await api<Grupo[]>('/grupos'));
    if (vista === 'opciones') { const [o, g] = await Promise.all([api<Opcion[]>('/opciones-whatsapp'), api<Grupo[]>('/grupos')]); setOpciones(o); setGrupos(g); }
    if (vista === 'usuarios') setCuentas(await api<Cuenta[]>('/usuarios'));
    if (vista === 'auditoria') setAuditoria(await api<Auditoria[]>('/auditoria'));
    if (vista === 'configuracion') setConfig(await api<Configuracion>('/configuracion/whatsapp'));
  } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo cargar'); } }; void cargar(); }, [vista, version, usuario.rol]);
  async function ejecutar(ruta: string, method: 'POST' | 'PATCH', cuerpo: unknown, limpiar?: () => void) {
    setBusy(true); setError(''); setExito('');
    try { await api(ruta, json(method, cuerpo)); limpiar?.(); setExito('Cambios guardados'); onChange(); }
    catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar'); }
    finally { setBusy(false); }
  }
  function crearGrupo(e: FormEvent) { e.preventDefault(); void ejecutar('/grupos', 'POST', { nombre: grupoNombre, descripcion: grupoDescripcion }, () => { setGrupoNombre(''); setGrupoDescripcion(''); }); }
  function crearOpcion(e: FormEvent) { e.preventDefault(); void ejecutar('/opciones-whatsapp', 'POST', { titulo: opTitulo, identificadorExterno: opCodigo, grupoId: Number(opGrupo), orden: Number(opOrden) }, () => { setOpTitulo(''); setOpCodigo(''); }); }
  function crearUsuario(e: FormEvent) { e.preventDefault(); void ejecutar('/usuarios', 'POST', { nombre, apellido, correo, password, rol }, () => { setNombre(''); setApellido(''); setCorreo(''); setPassword(''); }); }
  function crearAsesor(e: FormEvent) { e.preventDefault(); void ejecutar('/asesores', 'POST', { usuarioId: Number(asesorUsuario), grupoId: Number(asesorGrupo) }, () => setAsesorUsuario('')); }
  const titulos: Record<Vista, string> = { asesores: 'Asesores', grupos: 'Grupos', opciones: 'Opciones de WhatsApp', usuarios: 'Usuarios', configuracion: 'Configuración de WhatsApp', auditoria: 'Auditoría' };
  return <div className="p-5 md:p-8 max-w-7xl mx-auto"><div className="mb-7"><div className="eyebrow mb-2">Administración</div><h1 className="text-3xl font-bold">{titulos[vista]}</h1><p className="muted mt-2">{vista === 'asesores' ? 'Disponibilidad y reparto de consultas' : vista === 'opciones' ? 'Menú que recibe el cliente' : 'Gestión operativa del sistema'}</p></div>
    {error && <p role="alert" className="text-sm text-red-700 bg-red-50 p-3 rounded-lg mb-4">{error}</p>}{exito && <p role="status" className="text-sm text-green-700 bg-green-50 p-3 rounded-lg mb-4">{exito}</p>}
    {vista === 'asesores' && <><div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Asesor</th><th className="p-4">Grupo</th><th className="p-4">Estado</th><th className="p-4">Reparto</th><th className="p-4">Total</th><th className="p-4">Acción</th></tr></thead><tbody>{asesores.map(a => <tr key={a.id} className="border-t border-slate-100"><td className="p-4 font-semibold">{a.usuario.nombre} {a.usuario.apellido}<div className="font-normal muted text-xs">{a.usuario.correo}</div></td><td className="p-4">{a.grupo.nombre}</td><td className="p-4"><span className={`badge ${a.activoReparto && a.usuario.activo ? '' : 'badge-off'}`}>{a.activoReparto && a.usuario.activo ? 'Activo' : 'Inactivo'}</span></td><td className="p-4">{a.contadorReparto}</td><td className="p-4">{a.totalAsignaciones}</td><td className="p-4">{['ADMIN', 'RRHH'].includes(usuario.rol) && <button disabled={busy} className={`button ${a.activoReparto ? 'button-danger' : 'button-light'}`} onClick={() => void ejecutar(`/asesores/${a.id}/disponibilidad`, 'PATCH', { activoReparto: !a.activoReparto })}>{a.activoReparto ? 'Desactivar' : 'Activar'}</button>}</td></tr>)}</tbody></table></div>
      {usuario.rol === 'ADMIN' && <form onSubmit={crearAsesor} className="card p-5 mt-5 flex flex-wrap gap-3 items-end"><label className="text-sm flex-1 min-w-[190px]">Usuario asesor<select className="field mt-2" required value={asesorUsuario} onChange={e => setAsesorUsuario(e.target.value)}><option value="">Seleccionar</option>{cuentas.filter(c => c.rol === 'ASESOR' && !asesores.some(a => a.usuarioId === c.id)).map(c => <option key={c.id} value={c.id}>{c.nombre} {c.apellido}</option>)}</select></label><label className="text-sm flex-1 min-w-[190px]">Grupo<select className="field mt-2" required value={asesorGrupo} onChange={e => setAsesorGrupo(e.target.value)}><option value="">Seleccionar</option>{grupos.filter(g => g.activo).map(g => <option key={g.id} value={g.id}>{g.nombre}</option>)}</select></label><button className="button button-primary" disabled={busy}>Crear asesor</button></form>}</>}
    {vista === 'grupos' && <><div className="grid md:grid-cols-2 gap-4">{grupos.map(g => <div key={g.id} className="card p-5 flex justify-between gap-4"><div><h2 className="font-bold">{g.nombre}</h2><p className="text-sm muted mt-1">{g.descripcion || 'Sin descripción'}</p></div><span className={`badge h-fit ${g.activo ? '' : 'badge-off'}`}>{g.activo ? 'Activo' : 'Inactivo'}</span>{usuario.rol === 'ADMIN' && <button className="button button-light h-fit" disabled={busy} onClick={() => void ejecutar(`/grupos/${g.id}`, 'PATCH', { activo: !g.activo })}>{g.activo ? 'Desactivar' : 'Activar'}</button>}</div>)}</div>{usuario.rol === 'ADMIN' && <form onSubmit={crearGrupo} className="card p-5 mt-5 flex flex-wrap gap-3 items-end"><label className="text-sm flex-1 min-w-[180px]">Nombre<input className="field mt-2" required value={grupoNombre} onChange={e => setGrupoNombre(e.target.value)}/></label><label className="text-sm flex-1 min-w-[180px]">Descripción<input className="field mt-2" value={grupoDescripcion} onChange={e => setGrupoDescripcion(e.target.value)}/></label><button className="button button-primary" disabled={busy}>Crear grupo</button></form>}</>}
    {vista === 'opciones' && <><div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Orden</th><th className="p-4">Opción</th><th className="p-4">Identificador</th><th className="p-4">Grupo</th><th className="p-4">Estado</th><th className="p-4">Acción</th></tr></thead><tbody>{opciones.map(o => <tr key={o.id} className="border-t border-slate-100"><td className="p-4">{o.orden}</td><td className="p-4 font-semibold">{o.titulo}</td><td className="p-4 font-mono text-xs">{o.identificadorExterno}</td><td className="p-4">{o.grupo.nombre}</td><td className="p-4"><span className={`badge ${o.activo ? '' : 'badge-off'}`}>{o.activo ? 'Activa' : 'Inactiva'}</span></td><td className="p-4">{usuario.rol === 'ADMIN' && <button className="button button-light" disabled={busy} onClick={() => void ejecutar(`/opciones-whatsapp/${o.id}`, 'PATCH', { activo: !o.activo })}>{o.activo ? 'Desactivar' : 'Activar'}</button>}</td></tr>)}</tbody></table></div>{usuario.rol === 'ADMIN' && <form onSubmit={crearOpcion} className="card p-5 mt-5 grid md:grid-cols-5 gap-3 items-end"><label className="text-sm">Título<input className="field mt-2" required maxLength={24} value={opTitulo} onChange={e => setOpTitulo(e.target.value)}/></label><label className="text-sm">Código<input className="field mt-2" required value={opCodigo} onChange={e => setOpCodigo(e.target.value)}/></label><label className="text-sm">Grupo<select className="field mt-2" required value={opGrupo} onChange={e => setOpGrupo(e.target.value)}><option value="">Seleccionar</option>{grupos.filter(g => g.activo).map(g => <option key={g.id} value={g.id}>{g.nombre}</option>)}</select></label><label className="text-sm">Orden<input className="field mt-2" type="number" required value={opOrden} onChange={e => setOpOrden(e.target.value)}/></label><button className="button button-primary" disabled={busy}>Crear opción</button></form>}</>}
    {vista === 'usuarios' && <><div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Nombre</th><th className="p-4">Correo</th><th className="p-4">Rol</th><th className="p-4">Estado</th><th className="p-4">Acción</th></tr></thead><tbody>{cuentas.map(c => <tr key={c.id} className="border-t border-slate-100"><td className="p-4 font-semibold">{c.nombre} {c.apellido}</td><td className="p-4">{c.correo}</td><td className="p-4">{c.rol}</td><td className="p-4">{c.activo ? 'Activo' : 'Inactivo'}</td><td className="p-4"><button className="button button-light" disabled={busy || c.id === usuario.id} onClick={() => void ejecutar(`/usuarios/${c.id}`, 'PATCH', { activo: !c.activo })}>{c.activo ? 'Desactivar' : 'Activar'}</button></td></tr>)}</tbody></table></div><form onSubmit={crearUsuario} className="card p-5 mt-5 grid sm:grid-cols-2 lg:grid-cols-3 gap-3"><input aria-label="Nombre" className="field" placeholder="Nombre" required value={nombre} onChange={e => setNombre(e.target.value)}/><input aria-label="Apellido" className="field" placeholder="Apellido" required value={apellido} onChange={e => setApellido(e.target.value)}/><input aria-label="Correo" className="field" type="email" placeholder="Correo" required value={correo} onChange={e => setCorreo(e.target.value)}/><input aria-label="Contraseña" className="field" type="password" placeholder="Contraseña de al menos 12 caracteres" minLength={12} required value={password} onChange={e => setPassword(e.target.value)}/><select aria-label="Rol" className="field" value={rol} onChange={e => setRol(e.target.value as Rol)}>{(['ASESOR', 'RRHH', 'SUPERVISOR', 'ADMIN'] as Rol[]).map(r => <option key={r}>{r}</option>)}</select><button className="button button-primary" disabled={busy}>Crear usuario</button></form></>}
    {vista === 'configuracion' && <div className="card p-6 max-w-2xl"><div className="flex justify-between items-center mb-5"><span className="font-bold">Modo actual</span><span className="badge">{config?.modo.toUpperCase() || '—'}</span></div><div className="space-y-3 text-sm">{([['Phone Number ID', config?.phoneNumberIdConfigurado], ['WABA ID', config?.wabaIdConfigurado], ['Access Token', config?.accessTokenConfigurado], ['App Secret', config?.appSecretConfigurado], ['Webhook Verify Token', config?.verifyTokenConfigurado]] as Array<[string, boolean | undefined]>).map(([nombre, valor]) => <div key={nombre} className="flex justify-between py-2 border-t border-slate-100"><span>{nombre}</span><span className={valor ? 'text-green-700' : 'text-slate-500'}>{valor ? 'Configurado' : 'Pendiente'}</span></div>)}</div><div className="mt-5 p-4 bg-slate-50 rounded-lg text-sm"><div className="font-semibold mb-1">Webhook</div><code className="break-all">{config?.webhook || '—'}</code></div><p className="text-xs muted mt-4">Los secretos se administran exclusivamente mediante variables de entorno del servidor.</p></div>}
    {vista === 'auditoria' && <div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Fecha</th><th className="p-4">Responsable</th><th className="p-4">Acción</th><th className="p-4">Entidad</th></tr></thead><tbody>{auditoria.map(a => <tr key={a.id} className="border-t border-slate-100"><td className="p-4">{new Date(a.fecha).toLocaleString('es-PE')}</td><td className="p-4">{a.usuario ? `${a.usuario.nombre} ${a.usuario.apellido}` : 'Sistema'}</td><td className="p-4 font-semibold">{a.accion}</td><td className="p-4">{a.entidad} #{a.entidadId}</td></tr>)}</tbody></table></div>}
    {vista === 'asesores' && usuario.rol === 'ADMIN' && <AsesorEditor asesores={asesores} grupos={grupos} onChange={onChange}/ >}
    {vista === 'grupos' && usuario.rol === 'ADMIN' && <GrupoEditor grupos={grupos} onChange={onChange}/ >}
    {vista === 'opciones' && usuario.rol === 'ADMIN' && <OpcionEditor opciones={opciones} grupos={grupos} onChange={onChange}/ >}
  </div>;
}
