import assert from 'node:assert/strict';

const api = process.env.API_URL || 'http://localhost:4000';
const web = process.env.WEB_URL || 'http://localhost:3001';
const password = process.env.ADMIN_INICIAL_PASSWORD || 'DemoLocal!2026';

async function pedir(ruta, method = 'GET', cuerpo, cookie) {
  const respuesta = await fetch(`${api}${ruta}`, { method, headers: { ...(method !== 'GET' ? { Origin: web, 'Content-Type': 'application/json' } : {}), ...(cookie ? { Cookie: cookie } : {}) }, body: cuerpo ? JSON.stringify(cuerpo) : undefined });
  const dato = await respuesta.json().catch(() => ({}));
  if (!respuesta.ok) throw new Error(`${method} ${ruta}: ${respuesta.status} ${JSON.stringify(dato)}`);
  return { dato, cookie: respuesta.headers.get('set-cookie')?.split(';')[0] };
}

const health = await pedir('/salud');
assert.equal(health.dato.estado, 'ok');
const loginAdmin = await pedir('/auth/login', 'POST', { correo: 'admin@local.test', password });
const adminCookie = loginAdmin.cookie;
assert.ok(adminCookie);
const rrhhCookie = (await pedir('/auth/login', 'POST', { correo: 'rrhh@local.test', password })).cookie;
assert.ok(rrhhCookie);
assert.ok(Array.isArray((await pedir('/asesores', 'GET', undefined, rrhhCookie)).dato));
const rrhhConversaciones = await fetch(`${api}/conversaciones`, { headers: { Cookie: rrhhCookie } });
assert.equal(rrhhConversaciones.status, 403);
const supervisorCookie = (await pedir('/auth/login', 'POST', { correo: 'supervisor@local.test', password })).cookie;
assert.ok(Array.isArray((await pedir('/conversaciones', 'GET', undefined, supervisorCookie)).dato));
const sseAbort = new AbortController();
const sse = await fetch(`${api}/tiempo-real/eventos`, { headers: { Cookie: adminCookie }, signal: sseAbort.signal });
assert.equal(sse.status, 200);
const lectorSse = sse.body.getReader();
const eventoSse = (async () => { let texto = ''; while (!texto.includes('conversacion:actualizada')) { const { value, done } = await lectorSse.read(); if (done) throw new Error('SSE terminó sin evento'); texto += new TextDecoder().decode(value); } return texto; })();
const numero = `519${Date.now().toString().slice(-8)}`;
const bienvenida = (await pedir('/simulador/entrada', 'POST', { telefono: numero, tipo: 'TEXTO', contenido: 'Hola' })).dato;
assert.match(await Promise.race([eventoSse, new Promise((_, rechazar) => setTimeout(() => rechazar(new Error('SSE no entregó evento en 5 s')), 5000))]), /conversacion:actualizada/);
sseAbort.abort();
assert.equal(bienvenida[0].estado, 'ESPERANDO_OPCION');
const menu = bienvenida[0].mensajes.find(m => m.tipo === 'INTERACTIVO');
assert.ok(menu);
const opcion = JSON.parse(menu.contenido)[0];
const asignada = (await pedir('/simulador/entrada', 'POST', { telefono: numero, tipo: 'INTERACTIVO', contenido: opcion.titulo, opcionId: opcion.id })).dato[0];
assert.equal(asignada.estado, 'ABIERTA');
assert.ok(asignada.asesor?.usuario.nombre);
const asesorNombre = asignada.asesor.usuario.nombre.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase();
const loginAsesor = await pedir('/auth/login', 'POST', { correo: `${asesorNombre}@local.test`, password });
const asesorCookie = loginAsesor.cookie;
assert.ok(asesorCookie);
const lista = (await pedir('/conversaciones', 'GET', undefined, asesorCookie)).dato;
assert.ok(lista.some(c => c.id === asignada.id));
await pedir(`/conversaciones/${asignada.id}/mensajes`, 'POST', { contenido: 'Respuesta desde la bandeja' }, asesorCookie);
const historial = (await pedir(`/simulador/${numero}`)).dato[0];
assert.ok(historial.mensajes.some(m => m.contenido === 'Respuesta desde la bandeja'));
const asesores = (await pedir('/asesores', 'GET', undefined, adminCookie)).dato;
const otro = asesores.find(a => a.id !== asignada.asesor.id && a.grupoId === asignada.grupo.id);
assert.ok(otro);
const otroNombre = otro.usuario.nombre.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase();
const otroCookie = (await pedir('/auth/login', 'POST', { correo: `${otroNombre}@local.test`, password })).cookie;
const ajena = await fetch(`${api}/conversaciones/${asignada.id}`, { headers: { Cookie: otroCookie } });
assert.equal(ajena.status, 404);
await pedir(`/asesores/${asignada.asesor.id}/disponibilidad`, 'PATCH', { activoReparto: false }, rrhhCookie);
const numero2 = `518${Date.now().toString().slice(-8)}`;
await pedir('/simulador/entrada', 'POST', { telefono: numero2, tipo: 'TEXTO', contenido: 'Hola' });
const nueva = (await pedir('/simulador/entrada', 'POST', { telefono: numero2, tipo: 'INTERACTIVO', contenido: opcion.titulo, opcionId: opcion.id })).dato[0];
assert.notEqual(nueva.asesor?.id, asignada.asesor.id);
await pedir(`/asesores/${asignada.asesor.id}/disponibilidad`, 'PATCH', { activoReparto: true }, rrhhCookie);
await pedir(`/conversaciones/${asignada.id}/reasignar`, 'POST', { asesorId: otro.id, motivo: 'Prueba de supervisión' }, adminCookie);
const final = (await pedir(`/conversaciones/${asignada.id}`, 'GET', undefined, adminCookie)).dato;
assert.equal(final.asesorId, otro.id);
assert.equal(final.asignaciones.length, 2);
await pedir('/auth/logout', 'POST', {}, adminCookie);
const sesionCerrada = await fetch(`${api}/auth/me`, { headers: { Cookie: adminCookie } });
assert.equal(sesionCerrada.status, 401);
console.log(JSON.stringify({ ok: true, conversacion: asignada.id, asesorInicial: asignada.asesor.usuario.nombre, asesorFinal: otro.usuario.nombre, salud: health.dato }));
